Updated dependency and readme.
WondrousLLC/wondrous-stylelint-config pull request #1
Opened 2020-07-09 10:38 UTC by mirkopoloni

## Problem
When installing and using the package inside a project we have some 'unmet peer dependency' problems and the stylelint doesn't work.
e.g. `Error: Could not find "stylelint-order".`

This stylelint package is based on the `stylelint-config-sass-guidelines` (v.^4.1.0).
The 'unmet peer dependency' problems come from the `stylelint-config-sass-guidelines` package, this got some updates which will also fix the problem (i.e. v.5.0.0)

## Solution
To solve our problem we should update the version of the dependency in our package.json file.
There were multiple updates for the `stylelint-config-sass-guidelines` package, the main difference is the minimum required Node.js version.
`stylelint-config-sass-guidelines` versions:
- ^7.0.0  --> Node.js v10 or newer
- ^6.0.0 --> Node.js 8.7.0 or newer
- ^5.0.0 --> Node.js 6.x or newer

It is probably safer to update to version 5 because I don't know if we can assume that we always have/use a Node version greater than 6.

There aren't breaking changes for the `stylelint-config-sass-guidelines` version 5 update.
Here the most relevant:

[5.4.0]
- Fix patterns for variables like "$x1".
- Ignore all @-rules in max-nesting-depth.

[5.1.0]
- Ignore @each for max-nesting-depth.

[5.0.0]
- Added scss/at-rule-no-unknown rule.
- Added stylelint-scss and stylelint-order as dependencies.
- Node.js 6.x or greater is now required.

2020-07-09 11:56 UTC, yobottehg commented
@mirkopoloni i would do the following:
- Upgrade to the latest version.
- Tag a 2.0.0 release so that the old projects don't run into problems.
- Readme entry is not that required, just add the nodejs version requirement in the package json under engines

2020-07-09 11:56 UTC, rainer-friederich requested changes
see comment

2020-07-09 12:29 UTC, mirkopoloni commented
@yobottehg Should I also make a 1.4.3 Tag release and update the `stylelint-config-sass-guidelines` dependency there to version 5.0.0 to fix the problem or we do not need it?

2020-07-09 13:22 UTC, mirkopoloni commented
> @mirkopoloni i would do the following:
> 
> * Upgrade to the latest version.
> * Tag a 2.0.0 release so that the old projects don't run into problems.
> * Readme entry is not that required, just add the nodejs version requirement in the package json under engines

Changes done. Should I tag the 2.0.0 release before this pull request is merged? Or later on the master branch?

2020-07-10 06:42 UTC, yobottehg commented
> Should I also make a 1.4.3 Tag release and update the stylelint-config-sass-guidelines dependency there to version 5.0.0 to fix the problem or we do not need it?

Not needed now.

> Changes done. Should I tag the 2.0.0 release before this pull request is merged? Or later on the master branch?

After this was merged into master.

2020-07-10 06:42 UTC, yobottehg commented
Also for releases have a look at the package.json. there are scripts for it.

2020-08-20 15:02 UTC, mirkopoloni commented
@yobottehg Are the changes here okay? Can I do the release?

2020-08-21 08:13 UTC, rainer-friederich approved these changes

2020-08-21 08:13 UTC, merged